WITH final AS (
    SELECT
        id AS account_id,
        partner_id AS account_partner_id,
        collective_agreement_id AS account_collective_agreement_id,
        payroll_software_id AS account_payroll_software_id,
        name AS account_name,
        created_at AS account_created_at,
        updated_at AS account_updated_at,
        {{ timezone('country') }} AS account_timezone,
        default_language AS account_default_language,
        street AS account_street,
        zip AS account_zipcode,
        city AS account_city,
        country AS account_country,
        cheat_sheet_hour_cut AS account_sheet_hour_cut,
        social_tax AS account_social_tax,
        JSON_VALUE(preferences, '$.currency_iso_code') AS pref_currency_iso_code,
        JSON_VALUE(preferences, '$.planning_pdf_display_mode') AS pref_planning_pdf_display_mode,
        JSON_VALUE(preferences, '$.quadra_paie_separator') AS pref_quadra_paie_separator,
        CAST(JSON_VALUE(preferences, '$.productivity_objective') AS INT64) AS pref_productivity_objective,
        CAST(JSON_VALUE(preferences, '$.minimum_days_for_timeoff_request') AS INT64) AS pref_minimum_days_for_timeoff_request,
        COALESCE(CAST(blocked AS BOOL), FALSE) AS is_account_blocked,
        COALESCE(CAST(paid_breaks AS BOOL), FALSE) AS has_account_paid_breaks,
        COALESCE(CAST(show_real_and_planned_hours_on_planning AS BOOL), FALSE) AS is_account_showing_real_and_planned_hours_on_planning,
        COALESCE(CAST(JSON_VALUE(preferences, '$.allow_duplication_of_schedule_over_more_weeks') AS BOOL), FALSE) AS is_pref_allow_duplication_of_schedule_over_more_weeks,
        COALESCE(CAST(JSON_VALUE(preferences, '$.automatically_generate_employee_ids') AS BOOL), FALSE) AS is_pref_automatically_generate_employee_ids,
        COALESCE(CAST(JSON_VALUE(preferences, '$.director_can_read_paid_leave_dashboard') AS BOOL), FALSE) AS is_pref_director_can_read_paid_leave_dashboard,
        COALESCE(CAST(JSON_VALUE(preferences, '$.directors_can_access_dashboard_rh') AS BOOL), FALSE) AS is_pref_directors_can_access_dashboard_rh,
        COALESCE(CAST(JSON_VALUE(preferences, '$.display_rewards_on_memberpage') AS BOOL), FALSE) AS is_pref_display_rewards_on_memberpage,
        COALESCE(CAST(JSON_VALUE(preferences, '$.display_shifts_from_other_teams') AS BOOL), FALSE) AS is_pref_display_shifts_from_other_teams,
        COALESCE(CAST(JSON_VALUE(preferences, '$.display_signature_for_planning_pdf') AS BOOL), FALSE) AS is_pref_display_signature_for_planning_pdf,
        COALESCE(CAST(JSON_VALUE(preferences, '$.display_sunday_for_planning_pdf') AS BOOL), FALSE) AS is_pref_display_sunday_for_planning_pdf,
        COALESCE(CAST(JSON_VALUE(preferences, '$.display_week_hours_for_planning_pdf') AS BOOL), FALSE) AS is_pref_display_week_hours_for_planning_pdf,
        COALESCE(CAST(JSON_VALUE(preferences, '$.employee_can_read_coworker_planning') AS BOOL), FALSE) AS is_pref_employee_can_read_coworker_planning,
        COALESCE(CAST(JSON_VALUE(preferences, '$.employee_can_receive_sms_notification') AS BOOL), FALSE) AS is_pref_employee_can_receive_sms_notification,
        COALESCE(CAST(JSON_VALUE(preferences, '$.enabled_conversation') AS BOOL), FALSE) AS is_pref_conversation_enabled,
        COALESCE(CAST(JSON_VALUE(preferences, '$.hide_counters_alerts_planning_to_daily_worker') AS BOOL), FALSE) AS is_pref_hide_counters_alerts_planning_to_daily_worker,
        COALESCE(CAST(JSON_VALUE(preferences, '$.hide_weekly_rests_planning_unpublished') AS BOOL), FALSE) AS is_pref_hide_weekly_rests_planning_unpublished,
        COALESCE(CAST(JSON_VALUE(preferences, '$.hr_dashboard_access_granted') AS BOOL), FALSE) AS is_pref_hr_dashboard_access_granted,
        COALESCE(CAST(JSON_VALUE(preferences, '$.include_over_hours_in_wages') AS BOOL), FALSE) AS is_pref_include_over_hours_in_wages,
        COALESCE(CAST(JSON_VALUE(preferences, '$.lock_meals') AS BOOL), FALSE) AS is_pref_meals_locked,
        COALESCE(CAST(JSON_VALUE(preferences, '$.manager_can_access_to_payroll') AS BOOL), FALSE) AS is_pref_manager_can_access_to_payroll,
        COALESCE(CAST(JSON_VALUE(preferences, '$.manager_can_read_all_salaries') AS BOOL), FALSE) AS is_pref_manager_can_read_all_salaries,
        COALESCE(CAST(JSON_VALUE(preferences, '$.manager_can_read_paid_leave_dashboard') AS BOOL), FALSE) AS is_pref_manager_can_read_paid_leave_dashboard,
        COALESCE(CAST(JSON_VALUE(preferences, '$.manager_created_employees_plannable') AS BOOL), FALSE) AS is_pref_manager_created_employees_plannable,
        COALESCE(CAST(JSON_VALUE(preferences, '$.prevent_overlapping_pay_periods') AS BOOL), FALSE) AS is_pref_prevent_overlapping_pay_periods,
        COALESCE(CAST(JSON_VALUE(preferences, '$.report_evened_out_by_default') AS BOOL), FALSE) AS is_pref_report_evened_out_by_default,
        COALESCE(CAST(JSON_VALUE(preferences, '$.send_activities_report_mail_to_owner') AS BOOL), FALSE) AS is_pref_send_activities_report_mail_to_owner,
        COALESCE(CAST(JSON_VALUE(preferences, '$.uses_timeclock') AS BOOL), FALSE) AS is_pref_using_timeclock
    FROM
        {{ ref('accounts') }}
)

SELECT *
FROM final
