WITH final AS (
    SELECT
        account_id,
        account_partner_id,
        account_collective_agreement_id,
        account_payroll_software_id,
        account_name,
        account_created_at,
        account_updated_at,
        account_timezone,
        account_default_language,
        account_street,
        account_zipcode,
        account_city,
        account_country,
        account_sheet_hour_cut,
        account_social_tax,
        pref_currency_iso_code,
        pref_planning_pdf_display_mode,
        pref_quadra_paie_separator,
        pref_productivity_objective,
        pref_minimum_days_for_timeoff_request,
        is_account_blocked,
        has_account_paid_breaks,
        is_account_showing_real_and_planned_hours_on_planning,
        is_pref_allow_duplication_of_schedule_over_more_weeks,
        is_pref_automatically_generate_employee_ids,
        is_pref_director_can_read_paid_leave_dashboard,
        is_pref_directors_can_access_dashboard_rh,
        is_pref_display_rewards_on_memberpage,
        is_pref_display_shifts_from_other_teams,
        is_pref_display_signature_for_planning_pdf,
        is_pref_display_sunday_for_planning_pdf,
        is_pref_display_week_hours_for_planning_pdf,
        is_pref_employee_can_read_coworker_planning,
        is_pref_employee_can_receive_sms_notification,
        is_pref_conversation_enabled,
        is_pref_hide_counters_alerts_planning_to_daily_worker,
        is_pref_hide_weekly_rests_planning_unpublished,
        is_pref_hr_dashboard_access_granted,
        is_pref_include_over_hours_in_wages,
        is_pref_meals_locked,
        is_pref_manager_can_access_to_payroll,
        is_pref_manager_can_read_all_salaries,
        is_pref_manager_can_read_paid_leave_dashboard,
        is_pref_manager_created_employees_plannable,
        is_pref_prevent_overlapping_pay_periods,
        is_pref_report_evened_out_by_default,
        is_pref_send_activities_report_mail_to_owner,
        is_pref_using_timeclock
    FROM
        {{ ref('def_accounts') }}
)

SELECT *
FROM final
